# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  name: 'Pool3'

steps:
- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'SonarQubeConn1'
    organization: 'iwan1234'
    scannerMode: 'dotnet'
    projectKey: 'iwanbudiman_sonarcloud'
    projectName: 'sonarcloud'

- task: CmdLine@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    script: dotnet build --configuration $(buildConfiguration)

- task: SonarCloudAnalyze@4
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '300'